Update backend-ci-cd.yml

diff --git a/.github/workflows/backend-ci-cd.yml b/.github/workflows/backend-ci-cd.yml
--- a/.github/workflows/backend-ci-cd.yml
+++ b/.github/workflows/backend-ci-cd.yml
@@ -62,16 +62,27 @@ jobs:
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_BACKEND }}
       run: |
         ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
-        aws s3 cp s3://bami-practice-s3/path/to/bami-backend.tar /home/ec2-user/bami-backend.tar
+        set -e  # Exit immediately if a command exits with a non-zero status
+        echo "Downloading Docker image tar from S3..."
+        aws s3 cp s3://bami-practice-s3/path/to/bami-backend.tar /home/ec2-user/bami-backend.tar --region ap-northeast-2
+
+        echo "Loading Docker image..."
         docker load -i /home/ec2-user/bami-backend.tar
+
+        echo "Stopping existing Docker container if it exists..."
         docker stop bami-backend || true
         docker rm bami-backend || true
+
+        echo "Running new Docker container..."
         docker run -d -p 8080:8080 --name bami-backend \
           -e DB_URL=$(aws ssm get-parameter --name "/bami/DB_URL" --with-decryption --query "Parameter.Value" --output text) \
           -e DB_USERNAME=$(aws ssm get-parameter --name "/bami/DB_USERNAME" --query "Parameter.Value" --output text) \
           -e DB_PASSWORD=$(aws ssm get-parameter --name "/bami/DB_PASSWORD" --with-decryption --query "Parameter.Value" --output text) \
-          bami-backend:latest
+        bami-backend:latest
+
+        echo "Deployment completed successfully."
         EOF
+
     - name: Build with Gradle
       run: ./gradlew build -x test
       shell: bash
